# Site settings
title: Mr G
email: g@gg.com
description: > some stuff # this means to ignore newlines until "baseurl:"
baseurl: "/creative-theme-jekyll" # the subpath of your site, e.g. /blog/
url: "https://temp0st.net" # the base hostname & protocol for your site

twitter_username: @temp0st
github_username: @temp0st

# Build settings
markdown: kramdown
